### ISSUE TITLE
Unable to get registration token from database

### ISSUE THREAD

**Issue by papiveron** [jonashackt/docker-ci-stack#15]
This task doesn't get back any registration token in the **gitlab-runner.yaml** playbook :

```
- name: Extract Runner Registration Token directly from Gitlab DB
    become: true
    become_user: gitlab-psql
    vars:
        ansible_ssh_pipelining: true
        query: "SELECT runners_registration_token FROM application_settings ORDER BY id DESC LIMIT 1"
        psql_exec: "/opt/gitlab/embedded/bin/psql"
        gitlab_db_name: "gitlabhq_production"
    shell: '{{ psql_exec }} -h /var/opt/gitlab/postgresql/ -d {{ gitlab_db_name }} -t -A -c "{{ query }}"'
    register: gitlab_runner_registration_token_result
```
Cause the runners_registration_token column does not exist in the **application_settings** table. But the **runners_registration_token_encrypted** exists, however the **runners_registration_token_encrypted** string is rejected by runner-register api. So you have to copy runners registration token from the gitlab gui, hardcode it in the playbook and run the playbook again.

Did run into the same issue?
