### ISSUE TITLE
Typo at documentation: shell -> socket

### ISSUE THREAD

**Issue by KES777** [jonashackt/docker-ci-stack#19]
https://github.com/jonashackt/gitlab-ci-stack#changes-needed-in-gitlab-ciyml-for-docker-in-docker-compared-to-using-a-shell-runner-1
```
build-image:
  stage: build
  # the tag 'shell' advices only GitLab runners using this tag to pick up that job
  tags:
    - socket
  script:
    - docker build . --tag $REGISTRY_GROUP_PROJECT/gitlab-ci-shell-example:latest
```

Here `socket` tag is used, but commented as `shell`. Need to change: `shell` -> `socket`
