### ISSUE TITLE
gitlab-runner.yml: derive concurrency value from number of registered runners

### ISSUE THREAD

**Issue by jonashackt** [jonashackt/docker-ci-stack#6]
Right now, the both values aren´t coupled:
```
  - name: Register Gitlab-Runners using shell executor
    shell: "gitlab-runner register --non-interactive --url '{{gitlab_url}}' --registration-token '{{gitlab_runner_registration_token}}' --description '{{ item.name }}' --executor shell"
    with_items:
      - { name: shell-runner-1 }
      - { name: shell-runner-2 }
      - { name: shell-runner-3 }
      - { name: shell-runner-4 }
      - { name: shell-runner-5 }

  - name: set concurrent number of runners in gitlab-runner config
    ini_file:
      path: /etc/gitlab-runner/config.toml
      section: 
      option: concurrent
      value: 5
```

But if one adds another runner, the concurrency wouldn´t be updated automatically. Better provide a list of the runners to register somewhere and derive the concurrency value from that.
